version: '3.4'
services:
  aws:
    build: .
    image: flemay/aws:latest
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app

  musketeers:
    image: flemay/musketeers:latest
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /opt/app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    working_dir: /opt/app
