name: Push-Cookiecutter
on:
  push:
    branches:
      - master
    paths:
      - 'docker-cookiecutter/**'
  schedule:
    - cron: '0 6 4 * *'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push
        run: cd docker-cookiecutter && make ciPush
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
