name: Test Serverless
on:
  pull_request:
    paths:
      - 'docker-serverless/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: cd docker-serverless && make ciTest
